# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Coding - fans_medal_helper'
          repository: 'fans_medal_helper'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            ci-$(Build.BuildId)
            ci-latest
